# 异常

## 74.throw 和 throws 的区别？

throw：

表示方法内抛出某种异常对象
如果异常对象是非 RuntimeException 则需要在方法申明时加上该异常的抛出 即需要加上 throws 语句 或者 在方法体内 try catch 处理该异常，否则编译报错
执行到 throw 语句则后面的语句块不再执行
throws：

方法的定义上使用 throws 表示这个方法可能抛出某种异常
需要由方法的调用者进行异常处理

```java
package constxiong.interview;
 
import java.io.IOException;
 
public class TestThrowsThrow {
 
	public static void main(String[] args) {
		testThrows();
		
		Integer i = null;
		testThrow(i);
		
		String filePath = null;
		try {
			testThrow(filePath);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	/**
	 * 测试 throws 关键字
	 * @throws NullPointerException
	 */
	public static void testThrows() throws NullPointerException {
		Integer i = null;
		System.out.println(i + 1);
	}
	
	/**
	 * 测试 throw 关键字抛出 运行时异常
	 * @param i
	 */
	public static void testThrow(Integer i) {
		if (i == null) {
			throw new NullPointerException();//运行时异常不需要在方法上申明
		}
	}
	
	/**
	 * 测试 throw 关键字抛出 非运行时异常，需要方法体需要加 throws 异常抛出申明
	 * @param i
	 */
	public static void testThrow(String filePath) throws IOException {
		if (filePath == null) {
			throw new IOException();//运行时异常不需要在方法上申明
		}
	}
}
```

## 75.final、finally、finalize 有什么区别？

final可以用来修饰类、方法、变量，分别有不同的意义所在，final修饰的class代表不可继续扩展，final修饰的变量代表不可修改，final修饰的方法代表不可重写。

finally则是java保证某一段重点代码一定要被执行的修饰符，例如：我们需要用try块让JDBC保证连接，保证unlock锁等动作

finalize是基础类java.lang.Object的一个方法，它的设计目的是为了保证对象在垃圾回收之前完成特定资源的回收

如果你有关注过JAVA核心类库的基本API就会发现lang包下的很多类，相当一部分都被声明为了final class，就是因为一些安全问题的存在，让其他人在调用API的时候避免修改基础功能，可以保证平台的安全性。

而用final修饰变量也是同理，防止意外的去修改一些变量的值。

而从性能上来讲：
有助于JVM将方法进行内联，改善编译器进行条件编译的能力。

对于finally，明确知道如何使用即可，一般都是结合try块进行联合使用。

对于fnalize，我们要明确它是不推荐使用的，业界实践一再证明它不是个好的办法，在Java 9中，甚至明确将Object.fnalize()标记为deprecated！如果没有特别的原因，不要实 现fnalize方法，也不要指望利用它来进行资源回收。
为什么呢？简单说，你无法保证fnalize什么时候执行，执行的是否符合预期。使用不当会影响性能，导致程序死锁、挂起等。

## 76.try-catch-finally 中哪个部分可以省略？

catch 和 finally 语句块可以省略其中一个。

```java
package constxiong.interview;
 
public class TestOmitTryCatchFinally {
 
	public static void main(String[] args) {
		omitFinally();
		omitCatch();
	}
	
	/**
	 * 省略finally 语句块
	 */
	public static void omitFinally() {
		try {
			int i = 0;
			i += 1;
			System.out.println(i);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	/**
	 * 省略 catch 语句块
	 */
	public static void omitCatch() {
		int i = 0;
		try {
			i += 1;
		} finally {
			i = 10;
		}
		System.out.println(i);
	}
}
```

## 77.try-catch-finally 中，如果 catch 中 return 了，finally 还会执行吗？

会执行

1、不管有没有异常，finally中的代码都会执行
2、当try、catch中有return时，finally中的代码依然会继续执行
3、finally是在return后面的表达式运算之后执行的，此时并没有返回运算之后的值，而是把值保存起来，不管finally对该值做任何的改变，返回的值都不会改变，依然返回保存起来的值。也就是说方法的返回值是在finally运算之前就确定了的。
4、如果return的数据是引用数据类型，而在finally中对该引用数据类型的属性值的改变起作用，try中的return语句返回的就是在finally中改变后的该属性的值。
5、finally代码中最好不要包含return，程序会提前退出，也就是说返回的值不是try或catch中的值

## 78.常见的异常类有哪些？

- NullPointerException 当应用程序试图访问空对象时，则抛出该异常。
- SQLException 提供关于数据库访问错误或其他错误信息的异常。
- IndexOutOfBoundsException指示某排序索引（例如对数组、字符串或向量的排序）超出范围时抛出
- NumberFormatException当应用程序试图将字符串转换成一种数值类型，但该字符串不能转换为适当格式时，抛出该异常
- FileNotFoundException当试图打开指定路径名表示的文件失败时，抛出此异常。
- IOException当发生某种I/O异常时，抛出此异常。此类是失败或中断的I/O操作生成的异常的通用类。
- ClassCastException当试图将对象强制转换为不是实例的子类时，抛出该异常。
- ArrayStoreException试图将错误类型的对象存储到一个对象数组时抛出的异常。
- IllegalArgumentException 抛出的异常表明向方法传递了一个不合法或不正确的参数。
- ArithmeticException当出现异常的运算条件时，抛出此异常。例如，一个整数“除以零”时，抛出此类的一个实例。 
- NegativeArraySizeException如果应用程序试图创建大小为负的数组，则抛出该异常
- NoSuchMethodException无法找到某一特定方法时，抛出该异常。
- SecurityException由安全管理器抛出的异常，指示存在安全侵犯。
- UnsupportedOperationException当不支持请求的操作时，抛出该异常。
- RuntimeExceptionRuntimeException 是那些可能在Java虚拟机正常运行期间抛出的异常的超类。